services:
  fastapi-app:
    image: fastapi-image:latest
    container_name: fastapi-container
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    networks:
      - pinterest-network

  celery-worker:
    image: fastapi-image:latest
    container_name: celery-worker-container
    command: "celery -A app.celery.celery_app.celery_instance worker --loglevel=info"
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    networks:
      - pinterest-network

  celery-beat:
    image: fastapi-image:latest
    container_name: celery-beat-container
    command: "celery -A app.celery.celery_app.celery_instance beat --loglevel=info"
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    networks:
      - pinterest-network

  vuejs:
    image: vuejs-image:latest
    container_name: vuejs-container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pinterest-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/nginx:/var/log/nginx

networks:
  pinterest-network:
    external: true